import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Hero_section from '@/Components/Hero_section'
import How_laser_hair_removal_works from '@/Components/How_laser_hair_removal_works'
import Why_expert from '@/Components/Why_expert'
import Discount_offers from '@/Components/Discount_offers'
import Service_menue from '@/Components/Service_menue'
import Testimonials from '@/Components/Testimonials'
import Footer from '@/Components/Footer'
import Nav from '@/Components/Nav'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300&display=swap" rel="stylesheet"/>
      </Head>
<Nav/>     
<Hero_section/>
<How_laser_hair_removal_works/>
<Why_expert/>
<Discount_offers/>
<Service_menue/>
<Testimonials/>
<Footer/>

    </>
  )
}
